# Generated by Django 2.2.2 on 2019-06-13 00:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_area', models.CharField(choices=[('서울', '서울'), ('경기', '경기'), ('인천', '인천'), ('강원', '강원'), ('대전', '대전'), ('충남', '충남'), ('충북', '충북'), ('광주', '광주'), ('전남', '전남'), ('전북', '전북'), ('부산', '부산'), ('경남', '경남'), ('대구', '대구'), ('경북', '경북')], max_length=10)),
                ('arrive_area', models.CharField(choices=[('서울', '서울'), ('경기', '경기'), ('인천', '인천'), ('강원', '강원'), ('대전', '대전'), ('충남', '충남'), ('충북', '충북'), ('광주', '광주'), ('전남', '전남'), ('전북', '전북'), ('부산', '부산'), ('경남', '경남'), ('대구', '대구'), ('경북', '경북')], max_length=10)),
                ('departure_date', models.DateField(default=datetime.date.today)),
                ('departure_time', models.CharField(max_length=20)),
                ('detail_plan', models.CharField(max_length=100)),
                ('fee', models.CharField(max_length=30)),
                ('connect', models.CharField(max_length=50)),
                ('memo', models.CharField(max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
